name: 'Git Create/Update Tag'
description: 'Create or update Git tags on local or remote repositories. Supports GitHub, Gitea, Bitbucket, and generic Git hosts with optional GPG signing.'
author: 'LiquidLogicLabs'
inputs:
  tag-name:
    description: 'Name of the tag to create/update'
    required: true
  tag-message:
    description: 'Message for annotated tags. If provided, creates an annotated tag; if omitted, creates a lightweight tag'
    required: false
  tag-sha:
    description: 'Commit SHA to tag (defaults to current HEAD)'
    required: false
  repository:
    description: 'Repository URL or owner/repo format (defaults to current repo)'
    required: false
  token:
    description: 'Authentication token (defaults to GITHUB_TOKEN)'
    required: false
  update-existing:
    description: 'Whether to update existing tags (default: false)'
    required: false
    default: 'false'
  gpg-sign:
    description: 'Whether to GPG sign the tag (default: false)'
    required: false
    default: 'false'
  gpg-key-id:
    description: 'GPG key ID to use for signing'
    required: false
  repo-type:
    description: "Repository type ('github', 'gitea', 'bitbucket', 'generic', 'git', 'auto'). Default: 'auto' (auto-detect from repository URL). 'git' and 'generic' are equivalent aliases for local Git CLI operations."
    required: false
    default: 'auto'
  base-url:
    description: 'Base URL for self-hosted instances'
    required: false
  skip-certificate-check:
    description: 'Skip TLS certificate verification (default: false)'
    required: false
    default: 'false'
  force:
    description: 'Force update even if tag exists (default: false)'
    required: false
    default: 'false'
  verbose:
    description: 'Enable verbose/debug logging (default: false). Also enabled when ACTIONS_STEP_DEBUG, ACTIONS_RUNNER_DEBUG, or RUNNER_DEBUG is true.'
    required: false
    default: 'false'
  push-tag:
    description: 'Push the tag to the remote repository after creating/updating (default: true). Only applies when using local Git CLI.'
    required: false
    default: 'true'
  git-user-name:
    description: 'Git user name for annotated tags. Auto-detected from GITHUB_ACTOR/GITEA_ACTOR if not provided. Falls back to local git config.'
    required: false
  git-user-email:
    description: 'Git user email for annotated tags. Auto-detected from GITHUB_ACTOR/GITEA_ACTOR if not provided. Falls back to local git config.'
    required: false
outputs:
  tag-name:
    description: 'Name of the tag that was created/updated'
  tag-sha:
    description: 'SHA of the commit that was tagged'
  tag-exists:
    description: 'Whether the tag already existed (true/false)'
  tag-updated:
    description: 'Whether an existing tag was updated (true/false)'
  tag-created:
    description: 'Whether a new tag was created (true/false)'
  platform:
    description: 'Detected or specified platform (same as repo_type input or detected value)'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'blue'
