name: 'Git Create/Update Tag'
description: 'Create or update Git tags on local or remote repositories. Supports GitHub, Gitea, Bitbucket, and generic Git hosts with optional GPG signing.'
author: 'LiquidLogicLabs'
inputs:
  tagName:
    description: 'Name of the tag to create/update'
    required: true
  tagMessage:
    description: 'Message for annotated tags. If provided, creates an annotated tag; if omitted, creates a lightweight tag'
    required: false
  tagSha:
    description: 'Commit SHA to tag (defaults to current HEAD)'
    required: false
  repository:
    description: 'Repository URL or owner/repo format (defaults to current repo)'
    required: false
  token:
    description: 'Authentication token (defaults to GITHUB_TOKEN)'
    required: false
  updateExisting:
    description: 'Whether to update existing tags (default: false)'
    required: false
    default: 'false'
  gpgSign:
    description: 'Whether to GPG sign the tag (default: false)'
    required: false
    default: 'false'
  gpgKeyId:
    description: 'GPG key ID to use for signing'
    required: false
  repoType:
    description: "Repository type ('github', 'gitea', 'bitbucket', 'generic', 'git', 'auto'). Default: 'auto' (auto-detect from repository URL). 'git' and 'generic' are equivalent aliases for local Git CLI operations."
    required: false
    default: 'auto'
  baseUrl:
    description: 'Base URL for self-hosted instances'
    required: false
  skipCertificateCheck:
    description: 'Skip TLS certificate verification (default: false)'
    required: false
    default: 'false'
  force:
    description: 'Force update even if tag exists (default: false)'
    required: false
    default: 'false'
  verbose:
    description: 'Enable verbose/debug logging (default: false). Also enabled when ACTIONS_STEP_DEBUG=true.'
    required: false
    default: 'false'
  pushTag:
    description: 'Push the tag to the remote repository after creating/updating (default: true). Only applies when using local Git CLI.'
    required: false
    default: 'true'
  gitUserName:
    description: 'Git user name for annotated tags. Auto-detected from GITHUB_ACTOR/GITEA_ACTOR if not provided. Falls back to local git config.'
    required: false
  gitUserEmail:
    description: 'Git user email for annotated tags. Auto-detected from GITHUB_ACTOR/GITEA_ACTOR if not provided. Falls back to local git config.'
    required: false
outputs:
  tagName:
    description: 'Name of the tag that was created/updated'
  tagSha:
    description: 'SHA of the commit that was tagged'
  tagExists:
    description: 'Whether the tag already existed (true/false)'
  tagUpdated:
    description: 'Whether an existing tag was updated (true/false)'
  tagCreated:
    description: 'Whether a new tag was created (true/false)'
  platform:
    description: 'Detected or specified platform (same as repo_type input or detected value)'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'blue'

